name: template_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  introduction_screen: ^1.0.8
  #loading_hub
  loading_hud: ^0.2.0
  #detech when keyboard visibility or dismiss
  keyboard_visibility: 0.5.6
  flutter_keyboard_visibility: ^3.2.0
  #keyborad dismiss when click everywhere
  keyboard_dismisser: ^1.0.2
  #share_preferences save data local
  shared_preferences: ^0.5.7+2
  #step indicator
  step_progress_indicator: ^0.2.2+5
  #bottom_bar
  bottom_navy_bar: ^5.4.0
  #skeleton
  pk_skeleton: ^0.0.2
  skeleton_text: ^1.0.0
  #request permission
  permission_handler: ^5.0.0+hotfix.6
  #open app setting
  app_settings: 4.0.0
  #get lat lng
  geolocator: ^5.3.1
  #save data local NoSQL
  sembast: ^2.4.4+1
  #find commonly used locations on the filesystem
  path_provider: ^1.6.7
  #chart
  fl_chart: ^0.9.4
  #page transition
  page_transition: "^1.1.5"
  #firebase
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  #google sign
  google_sign_in: ^4.5.1
  #facebook sign
  flutter_facebook_login: ^3.0.0
  #cloud firestore
  cloud_firestore: ^0.13.6
  #date_picker
  flutter_datetime_picker: ^1.3.8
  #image picker
  image_picker: ^0.6.7+1
  #cached_image
  cached_network_image: ^2.2.0+1
  #map
  google_maps_flutter: ^0.5.28+1
  #flutter toast
  fluttertoast: ^4.0.0
  #multi image
  multi_image_picker: ^4.6.7
  #pin code
  pin_code_fields: ^3.1.2
  # font awesome
  font_awesome_flutter: ^8.8.1
  #carousel_slider
  carousel_slider: ^2.2.0
  #star rating
  smooth_star_rating: ^1.1.1
  #calendar schedule doctor
  flutter_calendar_carousel: ^1.4.12
  #pull to refresh
  pull_to_refresh: ^1.6.0
  #local push notification
  flutter_local_notifications: ^1.4.4+2
  #check network
  connectivity: ^0.4.9
  #stream
  rxdart: ^0.23.1
  #keyboard utils
  keyboard_utils: ^1.2.4
  #crop image
  image_cropper: ^1.2.3
  #recorder audio
  flutter_audio_recorder: ^0.5.5
  #player manager
  audioplayers: ^0.15.1
  #url_launcher
  url_launcher: ^5.5.0
  #
  get_it: ^4.0.2
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  photo_view: ^0.9.2
  firebase_messaging: ^6.0.16
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/data_search.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
